"""add reports table

Revision ID: d4f16d65c594
Revises: b2dff81a8a6d
Create Date: 2026-07-21 15:57:05.811792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f16d65c594'
down_revision: Union[str, Sequence[str], None] = 'b2dff81a8a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('product_module_filter', sa.String(length=30), nullable=True),
    sa.Column('customer_tier_filter', sa.String(length=20), nullable=True),
    sa.Column('generation_method', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
